# Generated by Django 4.0.5 on 2022-06-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=50)),
                ('student_last_name', models.CharField(max_length=50)),
                ('students_Age', models.IntegerField()),
                ('student_gender', models.CharField(max_length=30)),
                ('student_speciality', models.CharField(max_length=50)),
                ('student_laptop_type', models.CharField(max_length=50)),
                ('students_bio', models.TextField()),
            ],
        ),
    ]
